### ISSUE TITLE
Cassis cannot load a type system with types inheriting from "uima.tcas.DocumentAnnotation"

### ISSUE THREAD

**Issue by reckart** [dkpro/dkpro-cassis#142]
**Describe the bug**
Cassis cannot parse the attached type system.

[TS-DocumentAnnotationBug.xml.zip](https://github.com/dkpro/dkpro-cassis/files/5415536/TS-DocumentAnnotationBug.xml.zip)

**Expected behavior**
It should just work.

**Error message**
```
Traceback (most recent call last):
  File ".../sandbox.py", line 11, in <module>
    typesystem = load_typesystem(f)
  File ".../dkpro-cassis/cassis/typesystem.py", line 701, in load_typesystem
    return deserializer.deserialize(source)
  File ".../dkpro-cassis/cassis/typesystem.py", line 795, in deserialize
    t = types[type_name]
KeyError: 'uima.tcas.DocumentAnnotation'
```

**Comment by jcklie** [comment]
Solved via #143
