### ISSUE TITLE
Error if supertype has no namespace

### ISSUE THREAD

**Issue by reneverheij** [dkpro/dkpro-cassis#88]
I run into a KeyError while loading a type system (see attachment) exported by IBM Watson Explorer:

```
Traceback (most recent call last):
  File "C:/Users/x/PycharmProjects/dkpro-cassis/tests/load_wex_ts.py", line 12, in <module>
    typeSystem = load_typesystem(ts_descriptor_file)
  File "C:\Users\x\PycharmProjects\dkpro-cassis\cassis\typesystem.py", line 538, in load_typesystem
    return deserializer.deserialize(source)
  File "C:\Users\x\PycharmProjects\dkpro-cassis\cassis\typesystem.py", line 632, in deserialize
    t = types[type_name]
KeyError: 'OpinionPhrase'

Process finished with exit code 1
```

This error occurs while processing a type named OpinionPhrase, which does not have namespace.
It does not occur when I insert this code as lines 572 and 573:
```            
            if "." not in supertypeName:
                supertypeName = "uima.noNamespace." + supertypeName
```

However, this only means I get a second error later on. I don't know if it is related, but I describe it here anyway.
```
Traceback (most recent call last):
  File "C:/Users/x/PycharmProjects/dkpro-cassis/tests/load_wex_ts.py", line 12, in <module>
    typeSystem = load_typesystem(ts_descriptor_file)
  File "C:\Users\x\PycharmProjects\dkpro-cassis\cassis\typesystem.py", line 538, in load_typesystem
    return deserializer.deserialize(source)
  File "C:\Users\x\PycharmProjects\dkpro-cassis\cassis\typesystem.py", line 641, in deserialize
    t, name=f.name, rangeTypeName=f.rangeTypeName, elementType=f.elementType, description=f.description
  File "C:\Users\x\PycharmProjects\dkpro-cassis\cassis\typesystem.py", line 480, in add_feature
    type_.add_feature(feature)
  File "C:\Users\x\PycharmProjects\dkpro-cassis\cassis\typesystem.py", line 242, in add_feature
    self.__attrs_post_init__()
  File "C:\Users\x\PycharmProjects\dkpro-cassis\cassis\typesystem.py", line 175, in __attrs_post_init__
    self._constructor = attr.make_class(name, fields, bases=(FeatureStructure,), slots=True, eq=False, order=False)
  File "C:\Users\x\Anaconda3\lib\site-packages\attr\_make.py", line 2129, in make_class
    return _attrs(these=cls_dict, **attributes_arguments)(type_)
  File "C:\Users\x\Anaconda3\lib\site-packages\attr\_make.py", line 1002, in wrap
    builder.add_init()
  File "C:\Users\x\Anaconda3\lib\site-packages\attr\_make.py", line 689, in add_init
    self._is_exc,
  File "C:\Users\x\Anaconda3\lib\site-packages\attr\_make.py", line 1351, in _make_init
    bytecode = compile(script, unique_filename, "exec")
  File "<attrs generated init cassis.typesystem.com_ibm_es_tt_DocumentMetaData-19>", line 1
SyntaxError: duplicate argument 'self' in function definition

Process finished with exit code 1
```
The script it is trying to compile looks like this:
```
def __init__(self, xmiID=attr_dict['xmiID'].default, crawlspaceId=attr_dict['crawlspaceId'].default, crawlerId=attr_dict['crawlerId'].default, dataSource=attr_dict['dataSource'].default, dataSourceName=attr_dict['dataSourceName'].default, docType=attr_dict['docType'].default, encoding=attr_dict['encoding'].default, date=attr_dict['date'].default, url=attr_dict['url'].default, httpcode=attr_dict['httpcode'].default, documentId=attr_dict['documentId'].default, title=attr_dict['title'].default, deleteDocument=attr_dict['deleteDocument'].default, volatileURL=attr_dict['volatileURL'].default, associations=attr_dict['associations'].default, tags=attr_dict['tags'].default, type=attr_dict['type'].default, self=attr_dict['self'].default):
    self.xmiID = xmiID
    self.crawlspaceId = crawlspaceId
    self.crawlerId = crawlerId
    self.dataSource = dataSource
    self.dataSourceName = dataSourceName
    self.docType = docType
    self.encoding = encoding
    self.date = date
    self.url = url
    self.httpcode = httpcode
    self.documentId = documentId
    self.title = title
    self.deleteDocument = deleteDocument
    self.volatileURL = volatileURL
    self.associations = associations
    self.tags = tags
    self.type = type
    self.self = self
```
I'm working with conda 4.7.12 and python 3.7.4 on Windows 10.

[exported_typesystem.zip](https://github.com/dkpro/dkpro-cassis/files/3828588/exported_typesystem.zip)

**Comment by jcklie** [comment]
Thank you for the report and the fix! It works for me when I add it. The second error is caused because the feature is called `self` which is kinda a reserved name in python. You hit the jackpot with that I think. I will add some code and a warning that renames features temporarilty to `self_` .

**Comment by jcklie** [comment]
I opened a second issue for your second issue in #90 .

**Comment by jcklie** [comment]
Should be working, please reopen the issue if not.

**Comment by reneverheij** [comment]
I have verified that this problem has indeed been fixed. Thank you.
